### ISSUE TITLE
Can't test commit message starts with "\`"

### ISSUE THREAD

**Issue by SettingDust** [DanySK/gradle-pre-commit-git-hooks#89] opened 2022-05-26 03:29 UTC
### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Can't test commit message starts with "\`". Such as "fix(trigger): \`".  "fix(trigger): 1\`" is working

### Your configuration

https://github.com/EpicBanItemTeam/EpicBanItem/blob/develop/settings.gradle.kts
```
commitMsg {
    conventionalCommits()
}
```

### Gradle build scan and relevant logs

```
fix(trigger): `
Signed-off-by: SettingDust <0000000@000.com>
Your commit message does not follow Conventional Commits formatting: https://www.conventionalcommits.org/
Conventional Commits start with one of the following types:
fix feat build chore ci docs perf refactor revert style test
followed by an optional scope within parentheses,
followed by an exclamation mark (!) in case of breaking change,
followed by a colon (:),
followed by the commit message.
Example commit message fixing a bug non-breaking backwards compatibility:
fix(module): fix bug #42
Example commit message adding a non-breaking feature:
feat(module): add new API
Example commit message with a breaking change:
refactor(module)!: remove infinite loop
```

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by DanySK** [comment] 2022-05-26 08:58
Duplicate of #88

**Closed by DanySK** 2022-05-26 08:58 UTC
Labels: bug
